// GENERATED by scripts/sync-cb.mjs — do not edit.
//
// Sizes and nine-slice insets for the Casual Blue chrome, in SOURCE px. The
// art these describe is git-ignored (see NOTICE-casual-blue.md); this file is
// committed so the code around it stays readable and diffable without it.

/** source px → logical px; the pack is drawn at 2× the size we render it */
export const S = 0.5;

export const CB = {
  "button/button01_109_blue": {
    "w": 43,
    "h": 109,
    "slice": [
      18,
      20,
      22,
      20
    ],
    "as": "btn-blue"
  },
  "button/button01_109_gray": {
    "w": 43,
    "h": 109,
    "slice": [
      18,
      20,
      22,
      20
    ],
    "as": "btn-gray"
  },
  "button/button01_109_green": {
    "w": 43,
    "h": 109,
    "slice": [
      18,
      20,
      22,
      20
    ],
    "as": "btn-green"
  },
  "button/button01_109_red": {
    "w": 43,
    "h": 109,
    "slice": [
      18,
      20,
      22,
      20
    ],
    "as": "btn-red"
  },
  "button/button01_109_white_bg": {
    "w": 43,
    "h": 109,
    "slice": [
      18,
      20,
      22,
      20
    ],
    "as": "btn-white"
  },
  "button/button01_109_yellow": {
    "w": 43,
    "h": 109,
    "slice": [
      18,
      20,
      22,
      20
    ],
    "as": "btn-yellow"
  },
  "button/button01_85_blue": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-blue"
  },
  "button/button01_85_gray": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-gray"
  },
  "button/button01_85_green": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-green"
  },
  "button/button01_85_offwhite": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-offwhite"
  },
  "button/button01_85_red": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-red"
  },
  "button/button01_85_white_bg": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-white"
  },
  "button/button01_85_yellow": {
    "w": 42,
    "h": 85,
    "slice": [
      16,
      18,
      20,
      18
    ],
    "as": "btn85-yellow"
  },
  "button/button_circle_53": {
    "w": 53,
    "h": 53
  },
  "button/button_circle_60": {
    "w": 60,
    "h": 60
  },
  "button/button_round01_blue": {
    "w": 28,
    "h": 28,
    "slice": [
      11,
      13,
      14,
      13
    ]
  },
  "button/button_round01_white": {
    "w": 28,
    "h": 28,
    "slice": [
      11,
      13,
      14,
      13
    ]
  },
  "button/button_square01": {
    "w": 24,
    "h": 24
  },
  "frame/basicframe_round_12": {
    "w": 30,
    "h": 30,
    "slice": [
      13,
      13,
      13,
      13
    ]
  },
  "frame/borderframe_round_12_white_bg": {
    "w": 26,
    "h": 26,
    "slice": [
      12,
      12,
      12,
      12
    ]
  },
  "frame/borderframe_round_12_white_border": {
    "w": 32,
    "h": 32,
    "slice": [
      13,
      13,
      13,
      13
    ],
    "ring": true
  },
  "frame/itemframe03_round_10_bg": {
    "w": 24,
    "h": 24,
    "slice": [
      11,
      11,
      11,
      11
    ],
    "as": "card"
  },
  "frame/itemframe03_round_10_border": {
    "w": 34,
    "h": 34,
    "slice": [
      12,
      12,
      12,
      12
    ],
    "as": "card-border",
    "ring": true
  },
  "frame/itemframe03_round_10_focus": {
    "w": 43,
    "h": 43,
    "slice": [
      12,
      12,
      12,
      12
    ],
    "as": "card-focus",
    "ring": true
  },
  "frame/itemframe04_round_12_bg": {
    "w": 30,
    "h": 30,
    "slice": [
      12,
      12,
      12,
      12
    ],
    "as": "slot"
  },
  "frame/itemframe04_round_12_focusglow": {
    "w": 77,
    "h": 80,
    "slice": [
      12,
      12,
      12,
      12
    ],
    "as": "slot-glow",
    "ring": true
  },
  "frame/listframe01_round_12_bg": {
    "w": 30,
    "h": 30,
    "slice": [
      12,
      12,
      12,
      12
    ]
  },
  "frame/listframe01_round_12_focus": {
    "w": 45,
    "h": 48,
    "slice": [
      12,
      12,
      12,
      12
    ],
    "ring": true
  },
  "iconmisc/icon_add": {
    "w": 44,
    "h": 44
  },
  "iconmisc/icon_arrow01_back": {
    "w": 31,
    "h": 37
  },
  "iconmisc/icon_arrow01_next": {
    "w": 40,
    "h": 45
  },
  "iconmisc/icon_arrow_play": {
    "w": 38,
    "h": 44
  },
  "iconmisc/icon_check01": {
    "w": 46,
    "h": 43
  },
  "iconmisc/icon_close01": {
    "w": 34,
    "h": 37
  },
  "iconmisc/icon_close02_s": {
    "w": 34,
    "h": 34
  },
  "iconmisc/icon_coin01_s": {
    "w": 36,
    "h": 38
  },
  "iconmisc/icon_gem01": {
    "w": 38,
    "h": 40
  },
  "iconmisc/icon_home": {
    "w": 41,
    "h": 42
  },
  "iconmisc/icon_info_s": {
    "w": 11,
    "h": 31
  },
  "iconmisc/icon_lock01_l": {
    "w": 40,
    "h": 49
  },
  "iconmisc/icon_lock01_s": {
    "w": 34,
    "h": 41
  },
  "iconmisc/icon_music": {
    "w": 41,
    "h": 40
  },
  "iconmisc/icon_pause": {
    "w": 38,
    "h": 38
  },
  "iconmisc/icon_sound_btn": {
    "w": 46,
    "h": 42
  },
  "iconmisc/icon_trophy": {
    "w": 61,
    "h": 47
  },
  "item/itemicon_medal_bronze": {
    "w": 256,
    "h": 256
  },
  "item/itemicon_medal_gold": {
    "w": 256,
    "h": 256
  },
  "item/itemicon_medal_silver": {
    "w": 256,
    "h": 256
  },
  "item/itemicon_setting": {
    "w": 256,
    "h": 256
  },
  "label/label_rectangle_blue": {
    "w": 14,
    "h": 14,
    "slice": [
      6,
      6,
      6,
      6
    ]
  },
  "label/label_rectangle_gray": {
    "w": 14,
    "h": 14,
    "slice": [
      6,
      6,
      6,
      6
    ]
  },
  "label/label_rectangle_green": {
    "w": 14,
    "h": 14,
    "slice": [
      6,
      6,
      6,
      6
    ]
  },
  "label/label_rectangle_red": {
    "w": 14,
    "h": 14,
    "slice": [
      6,
      6,
      6,
      6
    ]
  },
  "label/label_rectangle_white_bg": {
    "w": 14,
    "h": 14,
    "slice": [
      6,
      6,
      6,
      6
    ]
  },
  "label/label_rectangle_yellow": {
    "w": 14,
    "h": 14,
    "slice": [
      6,
      6,
      6,
      6
    ]
  },
  "label/title_line_divider01_left": {
    "w": 14,
    "h": 11
  },
  "label/title_line_divider01_right": {
    "w": 14,
    "h": 11
  },
  "label/title_oval_48_bg": {
    "w": 52,
    "h": 48,
    "slice": [
      23,
      23,
      23,
      23
    ]
  },
  "label/title_oval_48_border": {
    "w": 52,
    "h": 48,
    "slice": [
      23,
      23,
      23,
      23
    ],
    "ring": true
  },
  "label/title_ribbon01_bg_blue": {
    "w": 99,
    "h": 59,
    "slice": [
      26,
      40,
      30,
      40
    ]
  },
  "label/title_ribbon01_bg_yellow": {
    "w": 99,
    "h": 59,
    "slice": [
      26,
      40,
      30,
      40
    ]
  },
  "popup/popup01-03_bg": {
    "w": 46,
    "h": 46,
    "slice": [
      20,
      20,
      24,
      20
    ],
    "as": "popup"
  },
  "popup/popup01-03_bg_top": {
    "w": 46,
    "h": 25,
    "slice": [
      10,
      20,
      12,
      20
    ],
    "as": "popup-top"
  },
  "popup/popup01-03_border": {
    "w": 46,
    "h": 46,
    "slice": [
      20,
      20,
      24,
      20
    ],
    "as": "popup-border",
    "ring": true
  },
  "slider/slider_parallelogram_21_bg": {
    "w": 14,
    "h": 20,
    "slice": [
      9,
      6,
      9,
      6
    ]
  },
  "slider/slider_parallelogram_21_fill_red": {
    "w": 11,
    "h": 17,
    "slice": [
      7,
      4,
      7,
      4
    ]
  },
  "slider/slider_parallelogram_21_fill_sky": {
    "w": 11,
    "h": 17,
    "slice": [
      7,
      4,
      7,
      4
    ]
  },
  "slider/slider_parallelogram_21_fill_yellow": {
    "w": 11,
    "h": 17,
    "slice": [
      7,
      4,
      7,
      4
    ]
  },
  "ui_etc/resourcebar_bg_white_bg": {
    "w": 18,
    "h": 42,
    "slice": [
      18,
      7,
      18,
      7
    ],
    "as": "pill"
  },
  "ui_etc/resourcebar_bg_white_border": {
    "w": 18,
    "h": 42,
    "slice": [
      18,
      7,
      18,
      7
    ],
    "as": "pill-border",
    "ring": true
  }
};

/** the css class sync-cb.mjs emitted for a sprite id */
export const cbClass = (id) => `cb-${CB[id]?.as ?? id.replace(/[/_]/g, "-")}`;
