/**
 * Recorded sound for the full game: every cue in ProcAudio is overridden with a
 * sample from public/audio/, generated by scripts/gen-audio.mjs (Scenario ->
 * ElevenLabs Sound Effects v2 and Music v2).
 *
 * The synth stays underneath as the base class rather than being deleted. A cue
 * fired before its buffer has decoded falls through to `super`, so the first
 * throw of a session is never silent, and the playable ads — which inline every
 * byte they ship and cannot afford a megabyte of mp3 — keep the synth outright.
 *
 * Samples are one recording per cue, so the parameters the old synth used to
 * express as frequency (combo pitch climbing, splashes scaled by impact) are
 * expressed as playback rate and gain instead. LEVEL holds the per-cue level
 * that puts the generated files back into a single mix, and CLIP the part of
 * each file worth playing.
 *
 * Anything that happens somewhere on the lake takes a world position and is
 * placed against the camera — see EAR. Cues that don't happen anywhere (menu
 * pips, the starting lights, fanfares, the workshop bench) pass no position and
 * play flat.
 */
import CUES from "./audiocues.json";
import { ProcAudio } from "./audioproc.js";

const IS_PLAYABLE =
  (typeof __PLAYABLE_SKIP__ !== "undefined" && !!__PLAYABLE_SKIP__) ||
  (typeof __PLAYABLE_CRAFT__ !== "undefined" && !!__PLAYABLE_CRAFT__);

const SFX_DIR = "audio/sfx";
const MUSIC_DIR = "audio/music";

const ALL_CUES = [...Object.entries(CUES.sfx), ...Object.entries(CUES.music)];

/**
 * Per-cue level, read from the same file the generator works off so the admin
 * panel's Audio Lab can tune the mix in one place. Every effect is levelled to
 * the same peak on the way out of the pipeline, which would be wrong for a game
 * left alone: a reel tick fires thirty times a second and a victory fanfare
 * fires once an hour. These are the trims that put them back in proportion.
 */
const LEVEL = Object.fromEntries(ALL_CUES.map(([id, c]) => [id, c.level]));

/**
 * The part of each file worth playing, as [start, end] in seconds.
 *
 * A generated clip is a fixed-length window the model fills as it sees fit, so
 * a one-shot routinely arrives with a tenth of a second of silence in front of
 * it and a long empty tail behind. Left alone that silence is latency: the
 * splash lands after the stone did. The Audio Lab writes these cut points on a
 * waveform and they're applied here, sample-accurate, at no cost — a buffer
 * source takes an offset and a duration anyway.
 *
 * Only cues that need cutting carry one, so a missing entry means play it all.
 *
 * Effects only. Music streams through an <audio> element instead of being
 * decoded, and an element can't be looped over a sub-range without seeking it
 * from a timeupdate handler, which fires four times a second and would put an
 * audible stumble in every loop. A music trim is cut into the file itself
 * instead — that's what the lab's bake button is for.
 */
const CLIP = Object.fromEntries(
  Object.entries(CUES.sfx).filter(([, c]) => c.clip).map(([id, c]) => [id, c.clip])
);

const SFX_NAMES = Object.keys(CUES.sfx);

/** slight detune on every shot so repeated cues don't sound like a loop */
const vary = (spread = 0.06) => 1 + (Math.random() * 2 - 1) * spread;

/**
 * How the lake carries sound to wherever the camera is standing.
 *
 * `ref` is the headroom the chase camera needs: it rides 7-12 units off the
 * player's own stone, so anything inside that stays at full volume and your own
 * throw never ducks itself. Everything past it falls away on an inverse curve,
 * which is what puts a rival skipping across the far bank in the background
 * instead of in your ear.
 *
 * Distance also takes the top off a sound, so far cues get a lowpass as well as
 * a trim — without it a quiet splash reads as a small splash rather than a
 * distant one. Panning is deliberately short of hard left/right; a stone that
 * slams into one ear as it passes the camera is disorienting on headphones.
 */
const EAR = {
  ref: 14,       // full volume inside this radius
  rolloff: 1,    // inverse-distance steepness past `ref`
  max: 160,      // beyond this a cue isn't worth the nodes; a hole is ~200 long
  width: 0.85,   // how far a fully off-axis sound is allowed to pan
  dullFrom: 40,  // where air starts eating the highs
  dullTo: 1400,  // lowpass corner (Hz) once a cue is at `max`
};

const FLAT = { gain: 1, pan: 0, cut: 0 };
const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);

export class SampleAudio extends ProcAudio {
  constructor() {
    super();
    this.buffers = new Map();
    this._music = null;      // { name, el, gain }
    this._musicWanted = null;
    this._musicRate = 1;
    this._loading = false;
  }

  _ensure() {
    const fresh = !this.ctx;
    super._ensure();
    if (!fresh || !this.ctx) return;
    this._load();
    // music streams, so it doesn't wait on the effects folder decoding
    if (this._musicWanted) this.playMusic(this._musicWanted, this._musicRate);
  }

  /**
   * Decode the whole effects folder on the first gesture. It is under a
   * megabyte all told and cues have to be instant once the game is running, so
   * there is nothing to gain from loading them one at a time.
   */
  async _load() {
    if (this._loading) return;
    this._loading = true;
    await Promise.all(SFX_NAMES.map(async (name) => {
      try {
        const res = await fetch(`${SFX_DIR}/${name}.mp3`);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        this.buffers.set(name, await this.ctx.decodeAudioData(await res.arrayBuffer()));
      } catch (e) {
        console.warn(`audio: ${name} unavailable, using synth`, e);
      }
    }));
    if (this.buffers.has("ambience")) this._startSampleAmbience();
  }

  /**
   * Where the ear is. The render loop already pulls the camera's world pose out
   * every frame for the rocks' eyes, so this is the same two values handed over
   * a second time rather than any new work.
   */
  setListener(pos, quat) {
    this._ear = { x: pos.x, y: pos.y, z: pos.z, qx: quat.x, qy: quat.y, qz: quat.z, qw: quat.w };
  }

  /**
   * Level, pan and dullness for a sound happening at `at`. Null means it's too
   * far away to be worth playing at all; FLAT means play it as authored, which
   * is what UI clicks and fanfares get since they don't happen anywhere.
   */
  _spatial(at) {
    const L = this._ear;
    if (!at || !L) return FLAT;

    const dx = at.x - L.x, dy = at.y - L.y, dz = at.z - L.z;
    const dist = Math.hypot(dx, dy, dz);
    if (dist > EAR.max) return null;
    if (dist < 0.001) return FLAT;

    // Rotate the offset into the camera's own frame — by the conjugate, since
    // we're going world -> listener — so the stereo image swings round with the
    // camera instead of being locked to the world's idea of east.
    const cx = -L.qx, cy = -L.qy, cz = -L.qz;
    const tx = 2 * (cy * dz - cz * dy);
    const ty = 2 * (cz * dx - cx * dz);
    const tz = 2 * (cx * dy - cy * dx);
    const rx = dx + L.qw * tx + (cy * tz - cz * ty);

    const fade = clamp((dist - EAR.dullFrom) / (EAR.max - EAR.dullFrom), 0, 1);
    return {
      gain: EAR.ref / (EAR.ref + EAR.rolloff * Math.max(0, dist - EAR.ref)),
      pan: clamp((EAR.width * rx) / dist, -1, 1),
      cut: fade > 0 ? 14000 * Math.pow(EAR.dullTo / 14000, fade) : 0,
    };
  }

  /**
   * Fire a one-shot. Returns false when the buffer isn't there yet, so the
   * caller can fall through to the synth — but true when the cue was placed out
   * of earshot, because that silence is the point and the synth must not undo it.
   */
  _shot(name, { rate = 1, gain = 1, delay = 0, at = null } = {}) {
    if (!this.ctx) return false;
    const space = this._spatial(at);
    if (!space) return true;
    const buf = this.buffers.get(name);
    if (!buf) return false;

    const t = this._now() + delay;
    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    src.playbackRate.value = rate;
    const g = this.ctx.createGain();
    g.gain.value = (LEVEL[name] ?? 0.5) * gain * space.gain;

    let tail = src.connect(g);
    if (space.cut) {
      const lp = this.ctx.createBiquadFilter();
      lp.type = "lowpass";
      lp.frequency.value = space.cut;
      tail = tail.connect(lp);
    }
    if (space.pan && this.ctx.createStereoPanner) {
      const p = this.ctx.createStereoPanner();
      p.pan.value = space.pan;
      tail = tail.connect(p);
    }
    tail.connect(this.master);
    const cut = CLIP[name];
    if (cut) src.start(t, cut[0], Math.max(0, cut[1] - cut[0]));
    else src.start(t);
    return true;
  }

  /**
   * The ambience sample was generated with loop=true, so it seams cleanly.
   * Crossfaded over the synth bed that has been holding the lake open since the
   * first gesture, rather than cutting between the two.
   */
  _startSampleAmbience() {
    const t = this._now();
    const src = this.ctx.createBufferSource();
    src.buffer = this.buffers.get("ambience");
    src.loop = true;
    // a clip on a looping cue moves the seam rather than ending the sound
    const cut = CLIP.ambience;
    if (cut) { src.loopStart = cut[0]; src.loopEnd = cut[1]; }
    const g = this.ctx.createGain();
    g.gain.setValueAtTime(0.0001, t);
    g.gain.linearRampToValueAtTime(LEVEL.ambience, t + 2);
    src.connect(g).connect(this.master);
    src.start(t, cut ? cut[0] : 0);

    const bed = this._ambienceBed;
    if (bed) {
      bed.gain.setValueAtTime(1, t);
      bed.gain.linearRampToValueAtTime(0, t + 2);
      const sources = this._ambienceSources || [];
      setTimeout(() => sources.forEach((s) => s.stop()), 2200);
      this._ambienceBed = null;
      this._ambienceSources = null;
    }
  }

  /** the synth bed only plays until the recording lands, then it's replaced */
  _startLakeAmbience() {
    if (!this.buffers.has("ambience")) super._startLakeAmbience();
  }

  // --- music ---

  /**
   * Streamed through an <audio> element rather than decoded like the effects:
   * the tracks are minutes long, and routing the element into the master gain
   * keeps them under the same mute and compressor as everything else.
   *
   * `rate` is how fast to spin the track — the higher race classes want a
   * quicker bed. Pitch rides along with it (see `_rate`) rather than being
   * held, so it reads as one tape running fast instead of two arrangements.
   */
  playMusic(name, rate = 1) {
    this._musicWanted = name;
    this._musicRate = rate;
    if (!this.ctx || !name) return;
    if (this._music?.name === name) { this._rate(this._music.el, rate); return; }

    const old = this._music;
    if (old) {
      const t = this._now();
      old.gain.gain.cancelScheduledValues(t);
      old.gain.gain.setValueAtTime(old.gain.gain.value, t);
      old.gain.gain.linearRampToValueAtTime(0.0001, t + 1.2);
      setTimeout(() => { old.el.pause(); old.gain.disconnect(); }, 1300);
    }

    const el = new window.Audio(`${MUSIC_DIR}/${name}.mp3`);
    el.loop = name !== "victory";
    el.crossOrigin = "anonymous";
    this._rate(el, rate);
    const gain = this.ctx.createGain();
    gain.gain.value = 0.0001;
    this.ctx.createMediaElementSource(el).connect(gain).connect(this.master);
    el.play().catch(() => {}); // a tab that never got a gesture just stays quiet
    const t = this._now();
    gain.gain.linearRampToValueAtTime(LEVEL[name] ?? 0.45, t + (old ? 1.6 : 2.5));
    this._music = { name, el, gain };
  }

  /**
   * Pitch has to follow the speed here. Browsers time-stretch by default, and a
   * stretched track sounds like the same tempo played through a fan — the lift
   * only lands when the whole thing rises with it.
   */
  _rate(el, rate) {
    el.preservesPitch = false;
    el.webkitPreservesPitch = false;
    el.playbackRate = rate;
  }

  stopMusic() {
    this._musicWanted = null;
    this._musicRate = 1;
    const m = this._music;
    if (!m) return;
    this._music = null;
    const t = this._now();
    m.gain.gain.cancelScheduledValues(t);
    m.gain.gain.setValueAtTime(m.gain.gain.value, t);
    m.gain.gain.linearRampToValueAtTime(0.0001, t + 1);
    setTimeout(() => { m.el.pause(); m.gain.disconnect(); }, 1100);
  }

  // --- one-off sfx ---

  throwWhoosh(power = 0.7, at = null) {
    if (!this._shot("throw", { at, rate: (0.92 + 0.28 * power) * vary(0.04), gain: 0.45 + 0.55 * power })) {
      super.throwWhoosh(power);
    }
  }

  /** the combo climbs a semitone at a time, the way the synth plink used to */
  skip(n = 1, power = 0.7, at = null) {
    const rate = Math.pow(1.055, Math.min(n, 10)) * vary(0.03);
    if (!this._shot("skip", { at, rate, gain: 0.6 + 0.4 * power })) super.skip(n, power);
  }

  settle(at = null) { if (!this._shot("settle", { at, rate: vary() })) super.settle(); }
  sink(at = null) { if (!this._shot("sink", { at, rate: vary(0.05) })) super.sink(); }
  blast(at = null) { if (!this._shot("blast", { at, rate: vary(0.05) })) super.blast(); }

  boing(n = 1, at = null) {
    if (!this._shot("boing", { at, rate: (1 + Math.min(n, 8) * 0.035) * vary(0.03) })) super.boing(n);
  }

  thunk(at = null) { if (!this._shot("thunk", { at, rate: vary() })) super.thunk(); }

  headKnock(kind = "bridge", at = null) {
    const name = kind === "cave" ? "knockstone" : "knockwood";
    if (!this._shot(name, { at, rate: vary() })) super.headKnock(kind);
  }

  paddleWhack(flung = true, at = null) {
    if (!this._shot("paddle", { at, rate: (flung ? 1.06 : 0.94) * vary(0.04), gain: flung ? 1 : 0.8 })) {
      super.paddleWhack(flung);
    }
  }

  plunge(drop = 5, at = null) {
    const d = Math.min(1, drop / 8);
    if (!this._shot("plunge", { at, rate: 1.08 - 0.16 * d, gain: 0.6 + 0.4 * d })) super.plunge(drop);
  }

  iceSlide(speed = 10, at = null) {
    const s = Math.min(1, speed / 18);
    if (!this._shot("iceslide", { at, rate: 0.9 + 0.3 * s, gain: 0.6 + 0.4 * s })) super.iceSlide(speed);
  }

  weedDrag(thick = 1, at = null) {
    if (!this._shot("weeds", { at, rate: vary(0.05), gain: 0.5 + 0.5 * Math.min(1, thick) })) super.weedDrag(thick);
  }

  deckLand(at = null) { if (!this._shot("deck", { at, rate: vary() })) super.deckLand(); }
  reelTick() { if (!this._shot("reel", { rate: vary(0.12) })) super.reelTick(); }
  catchRock() { if (!this._shot("catch")) super.catchRock(); }
  fishMiss() { if (!this._shot("fishmiss")) super.fishMiss(); }

  pip(up = true) { if (!this._shot("pip", { rate: up ? 1.06 : 0.86 })) super.pip(up); }
  startLight(i) { if (!this._shot("light", { rate: 1 + i * 0.09 })) super.startLight(i); }
  startGo() { if (!this._shot("go")) super.startGo(); }

  grind() { if (!this._shot("grind", { rate: vary(0.18) })) super.grind(); }
  coreClank() { if (!this._shot("clank", { rate: vary(0.15) })) super.coreClank(); }
  paintDab() { if (!this._shot("paint", { rate: vary(0.15) })) super.paintDab(); }
  pickRock() { if (!this._shot("pick", { rate: vary(0.1) })) super.pickRock(); }
  gull() { if (!this._shot("gull", { rate: vary(0.1) })) super.gull(); }

  holeWin(mine = true) {
    if (!this._shot(mine ? "holewin" : "holelose")) super.holeWin(mine);
  }

  win() { if (!this._shot("win")) super.win(); }
  lose() { if (!this._shot("lose")) super.lose(); }
  splashed(at = null) { if (!this._shot("splashed", { at, rate: vary(0.06) })) super.splashed(); }
}

export const audio = IS_PLAYABLE ? new ProcAudio() : new SampleAudio();
